function newData1=importpp(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 22-May-2012 22:36:11

DELIMITER = ' ';
HEADERLINES = 62;

% Import the file
newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);
newData1=newData1.data;
% Create new variables in the base workspace from those fields.
% vars = fieldnames(newData1);
% for i = 1:length(vars)
%     assignin('read_mc3e_txt', vars{i}, newData1.(vars{i}));
% end

